// Mocks generated by Mockito 5.4.6 from annotations
// in crewmeister_frontend_coding_challenge/test/features/absences/presentation/bloc/absences_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:crewmeister_frontend_coding_challenge/features/absences/domain/entities/member.dart'
    as _i6;
import 'package:crewmeister_frontend_coding_challenge/features/absences/domain/repositories/absence_repository.dart'
    as _i2;
import 'package:crewmeister_frontend_coding_challenge/features/absences/domain/usecases/get_absences_usecase.dart'
    as _i3;
import 'package:crewmeister_frontend_coding_challenge/features/absences/domain/usecases/get_members_usecase.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAbsenceRepository_0 extends _i1.SmartFake
    implements _i2.AbsenceRepository {
  _FakeAbsenceRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAbsencesResultModel_1 extends _i1.SmartFake
    implements _i3.AbsencesResultModel {
  _FakeAbsencesResultModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAbsencesRepositoryResult_2 extends _i1.SmartFake
    implements _i2.AbsencesRepositoryResult {
  _FakeAbsencesRepositoryResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetAbsencesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAbsencesUseCase extends _i1.Mock
    implements _i3.GetAbsencesUseCase {
  MockGetAbsencesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AbsenceRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAbsenceRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AbsenceRepository);

  @override
  _i4.Future<_i3.AbsencesResultModel> execute({
    int? page = 1,
    int? pageSize = 10,
    List<String>? types,
    List<String>? statuses,
    DateTime? startDate,
    DateTime? endDate,
    String? memberName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #page: page,
              #pageSize: pageSize,
              #types: types,
              #statuses: statuses,
              #startDate: startDate,
              #endDate: endDate,
              #memberName: memberName,
            }),
            returnValue: _i4.Future<_i3.AbsencesResultModel>.value(
              _FakeAbsencesResultModel_1(
                this,
                Invocation.method(#execute, [], {
                  #page: page,
                  #pageSize: pageSize,
                  #types: types,
                  #statuses: statuses,
                  #startDate: startDate,
                  #endDate: endDate,
                  #memberName: memberName,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.AbsencesResultModel>);
}

/// A class which mocks [GetMembersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMembersUseCase extends _i1.Mock implements _i5.GetMembersUseCase {
  MockGetMembersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AbsenceRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAbsenceRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AbsenceRepository);

  @override
  _i4.Future<List<_i6.Member>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i4.Future<List<_i6.Member>>.value(<_i6.Member>[]),
          )
          as _i4.Future<List<_i6.Member>>);
}

/// A class which mocks [AbsenceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbsenceRepository extends _i1.Mock implements _i2.AbsenceRepository {
  MockAbsenceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AbsencesRepositoryResult> getAbsences({
    required int? page,
    required int? pageSize,
    List<String>? types,
    List<String>? statuses,
    DateTime? startDate,
    DateTime? endDate,
    String? memberName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAbsences, [], {
              #page: page,
              #pageSize: pageSize,
              #types: types,
              #statuses: statuses,
              #startDate: startDate,
              #endDate: endDate,
              #memberName: memberName,
            }),
            returnValue: _i4.Future<_i2.AbsencesRepositoryResult>.value(
              _FakeAbsencesRepositoryResult_2(
                this,
                Invocation.method(#getAbsences, [], {
                  #page: page,
                  #pageSize: pageSize,
                  #types: types,
                  #statuses: statuses,
                  #startDate: startDate,
                  #endDate: endDate,
                  #memberName: memberName,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.AbsencesRepositoryResult>);

  @override
  _i4.Future<List<_i6.Member>> getMembers() =>
      (super.noSuchMethod(
            Invocation.method(#getMembers, []),
            returnValue: _i4.Future<List<_i6.Member>>.value(<_i6.Member>[]),
          )
          as _i4.Future<List<_i6.Member>>);
}
