// Mocks generated by Mockito 5.4.6 from annotations
// in crewmeister_frontend_coding_challenge/test/features/absences/domain/usecases/get_members_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:crewmeister_frontend_coding_challenge/features/absences/domain/entities/member.dart'
    as _i4;
import 'package:crewmeister_frontend_coding_challenge/features/absences/domain/repositories/absence_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAbsencesRepositoryResult_0 extends _i1.SmartFake
    implements _i2.AbsencesRepositoryResult {
  _FakeAbsencesRepositoryResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AbsenceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbsenceRepository extends _i1.Mock implements _i2.AbsenceRepository {
  @override
  _i3.Future<_i2.AbsencesRepositoryResult> getAbsences({
    required int? page,
    required int? pageSize,
    List<String>? types,
    List<String>? statuses,
    DateTime? startDate,
    DateTime? endDate,
    String? memberName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAbsences, [], {
              #page: page,
              #pageSize: pageSize,
              #types: types,
              #statuses: statuses,
              #startDate: startDate,
              #endDate: endDate,
              #memberName: memberName,
            }),
            returnValue: _i3.Future<_i2.AbsencesRepositoryResult>.value(
              _FakeAbsencesRepositoryResult_0(
                this,
                Invocation.method(#getAbsences, [], {
                  #page: page,
                  #pageSize: pageSize,
                  #types: types,
                  #statuses: statuses,
                  #startDate: startDate,
                  #endDate: endDate,
                  #memberName: memberName,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.AbsencesRepositoryResult>.value(
                  _FakeAbsencesRepositoryResult_0(
                    this,
                    Invocation.method(#getAbsences, [], {
                      #page: page,
                      #pageSize: pageSize,
                      #types: types,
                      #statuses: statuses,
                      #startDate: startDate,
                      #endDate: endDate,
                      #memberName: memberName,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.AbsencesRepositoryResult>);

  @override
  _i3.Future<List<_i4.Member>> getMembers() =>
      (super.noSuchMethod(
            Invocation.method(#getMembers, []),
            returnValue: _i3.Future<List<_i4.Member>>.value(<_i4.Member>[]),
            returnValueForMissingStub: _i3.Future<List<_i4.Member>>.value(
              <_i4.Member>[],
            ),
          )
          as _i3.Future<List<_i4.Member>>);
}
